AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::Serverless-2016-10-31"
Description: AWS IoT Core Sample
Parameters:
  ProjectPrefix:
    Type: String
    Default: ""

  CertificateArn:
    Type: String

Resources:
  #-------------------------------------------------------
  #   IoT Core
  #-------------------------------------------------------
  Thing1:
    Type: AWS::IoT::Thing
    Properties:
      ThingName: !Sub ${ProjectPrefix}Thing1

  Policy:
    Type: AWS::IoT::Policy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - iot:Connect
            Resource:
              - !Sub arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:client/*
          - Effect: Allow
            Action:
              - iot:Publish
            Resource:
              - !Sub arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:topic/*
          - Effect: Allow
            Action:
              - iot:Subscribe
            Resource:
              - !Sub arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:topicfilter/*
          - Effect: Allow
            Action:
              - iot:Receive
            Resource:
              - !Sub arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:topic/*
      PolicyName: !Sub ${ProjectPrefix}Policy

  PolicyPrincipalAttachment:
    Type: AWS::IoT::PolicyPrincipalAttachment
    Properties:
      PolicyName: !Ref Policy
      Principal: !Sub ${CertificateArn}

  ThingPrincipalAttachment:
    Type: AWS::IoT::ThingPrincipalAttachment
    Properties:
      Principal: !Sub ${CertificateArn}
      ThingName: !Ref Thing1
