AWSTemplateFormatVersion: 2010-09-09
Description: AWS IoT Core Sample
Parameters:
  ProjectPrefix:
    Type: String
    Default: ""

  CertificateArn:
    Type: String

Resources:
  #-------------------------------------------------------
  #   IoT Core
  #-------------------------------------------------------
  IoTCoreJobThing:
    Type: AWS::IoT::Thing
    Properties:
      ThingName: !Sub ${ProjectPrefix}IoTCoreJobThing

  Policy:
    Type: AWS::IoT::Policy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - iot:Connect
            Resource:
              - !Sub arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:client/*
          - Effect: Allow
            Action:
              - iot:Publish
            Resource:
              - !Sub arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:topic/*
          - Effect: Allow
            Action:
              - iot:Subscribe
            Resource:
              - !Sub arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:topicfilter/*
          - Effect: Allow
            Action:
              - iot:Receive
            Resource:
              - !Sub arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:topic/*
      PolicyName: !Sub ${ProjectPrefix}IoTCoreJobPolicy

  PolicyPrincipalAttachment:
    Type: AWS::IoT::PolicyPrincipalAttachment
    Properties:
      PolicyName: !Ref Policy
      Principal: !Sub ${CertificateArn}

  ThingPrincipalAttachment:
    Type: AWS::IoT::ThingPrincipalAttachment
    Properties:
      Principal: !Sub ${CertificateArn}
      ThingName: !Ref IoTCoreJobThing

  S3DownloadRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: iot.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: s3:GetObject
                Resource: "*"

Outputs:
  IoTCoreJobThing:
    Value: !GetAtt IoTCoreJobThing.Arn

  S3DownloadRole:
    Value: !GetAtt S3DownloadRole.Arn
